### ISSUE TITLE
How to continue training?

### ISSUE THREAD

**Issue by ChuhanWang10** [cwchenwang/NeRF-SR#1]
Hi, 

The work looks nice! I did some training by myself, however, I could not resume the training after losing the connection to the Colab. I find that there are options for "--continue_train" and setting "load_epoch" to resume from a specific epoch. I add these lines in the train_llff_downX file, but it does not work. 

![image](https://user-images.githubusercontent.com/80790361/181780653-2bd8b07f-99fc-4725-915f-5ee1fbf22bbd.png)

Can you tell me how to resume the training? Thank you！

**Comment by cwchenwang** [comment]
Could you tell me what problem you have (for example, the screenshot for the error) ?

**Comment by ChuhanWang10** [comment]
> Could you tell me what problem you have (for example, the screenshot for the error) ?
Hey I have already fixed it. It was a silly question. It should be added like this:

![image](https://user-images.githubusercontent.com/80790361/181840789-391c26ee-2cb5-4ee1-b434-fc2a66d75b87.png)

I will close this issue.
