### ISSUE TITLE
How can I get SSIM and LPILS data?

### ISSUE THREAD

**Issue by xqq21** [cwchenwang/NeRF-SR#10]

**Comment by cwchenwang** [comment]
sorry, I don't quite understand your question. Do you mean how to evaluate SSIM and LPIPS?

**Comment by xqq21** [comment]
Yes, when I render the pretrained model, I only find  the evaluation of PSNR in the logs.

**Comment by cwchenwang** [comment]
You can use ssim in skimage and lpips package in python to do that.
