### ISSUE TITLE
Question about table 1 and table 2 

### ISSUE THREAD

**Issue by william0620** [cwchenwang/NeRF-SR#3]
Hi, I'm very interested in your essay, I'd like to ask which specific dataset you'd used to hang out the result, like lego, chais, drums, etc. Or you just average the result. Thanks a lot!!

**Comment by cwchenwang** [comment]
We evaluated on two common datasets for NeRF: LLFF (contain scenes like fern) and Blender (contain scenes like lego). The results for both dataset are calculated by averaging the results for all the scenes in the dataset.

**Comment by william0620** [comment]
ok, thanks a lot!
