### ISSUE TITLE
Question about your paper.

### ISSUE THREAD

**Issue by qhdqhd** [cwchenwang/NeRF-SR#5]
Thanks for your nice work!
I think you should compare with mip-nerf, cause both of you are doing the same thing.
![X47}EDT0IPP(LJ$A52(S7JB](https://user-images.githubusercontent.com/42370719/223976787-d8cfa7c6-5929-4e0d-82d9-4f84e7d16bf3.png)

**Comment by qhdqhd** [comment]
https://github.com/google/mipnerf/issues/15
Well I find this, it is very interesting......But why?

**Comment by cwchenwang** [comment]
Thanks for bringing this out. Actually I am not quite sure why this happens. It seems that current Nerfstudio can run high-res views without problem with IPE. So it might because of the forward-facing data?

**Comment by qhdqhd** [comment]
Thanks for your nice reply.
I have another question.
I am testing nerfacto now.  My input views are 750x750,and my render views are 1500x1500, and its PSNR is 23.72dB.
So i am considering supersampling. First, I reisze input views from 750x750 to 1500x1500 using bilinear. Then I train the resized views and render 1500x1500 views, but its PSNR is 22.97dB，which is worse.
Well, I can not understand why? Can you explain it?

**Comment by qhdqhd** [comment]
![6NP2@(8TS@_{LU_F0%X96E5](https://user-images.githubusercontent.com/42370719/224242557-dfe55b89-5566-45f5-b55f-89dc2ef708c3.png)
This is the way you use supersample, which seems more reasonable than above bilinear.

**Comment by qhdqhd** [comment]
By  the way, can your method beat mipnerf when the render resolution is the same as input resolution?
Because I found mipnerf also test supersample. And mipnerf behave almost the same as supersample but much more faster!
![@CXO$R(@8 @ $R$4~$X4XY8](https://user-images.githubusercontent.com/42370719/224243525-60c3ffb2-30e3-4514-8a54-e96d454bd07d.png)

**Comment by cwchenwang** [comment]
> m testing nerfacto now. My input views are 750x750,and my r

What dataset did you use for this experiment? Maybe you can try some other upsampling methods other than bilinear.

**Comment by cwchenwang** [comment]
> You did a good job. By the way, can your method beat mipnerf when the render resolution is the same as input resolution?（sorry I am a little doubt） Because I found mipnerf also compare with supersample+NeRF. And mipnerf behave almost the same as supersample but much more faster! And the supersample way seems different, mipnerf just train and render on HR image, then just downsample HR to LR, then evaluate PSNR on LR images, which is too simple and crude? ![@CXO$R(@8 @ $R$4~$X4XY8](https://user-images.githubusercontent.com/42370719/224243525-60c3ffb2-30e3-4514-8a54-e96d454bd07d.png) ![RWAG)DO7A)T{8@G~B3J0F34](https://user-images.githubusercontent.com/42370719/224243688-ed5f8144-c9e0-4842-8a2b-d70dbde70354.png)

I guess on the same input resolution, our method is not guaranteed to be better but might achieve similar performance (I am also not sure though). The supersampling in mipnerf is a little different from ours, we test on HR images but mipnerf's ss doesn't try to generalize to resolutions higher than input. Anyway, supersampling can be incorporated into mipnerf or even instant-ngp.

**Comment by qhdqhd** [comment]
> > 我现在正在测试 nerfacto。我的输入视图是 750x750，我的 r
> 
> 你在这个实验中使用了什么数据集？也许你可以尝试一些除了双线性之外的其他上采样方法。

My own datasets. 
So in your opinion, it also strange?
Did you try the experiments before?
The only reason I can infer is that your supervise method on subpixel is the right way. My bilinear method is wrong.

**Comment by cwchenwang** [comment]
> > > 我现在正在测试 nerfacto。我的输入视图是 750x750，我的 r
> > 
> > 
> > 你在这个实验中使用了什么数据集？也许你可以尝试一些除了双线性之外的其他上采样方法。
> 
> My own datasets. So in your opinion, it also strange? Did you try the experiments before? The only reason I can infer is that your supervise method on subpixel is the right way. My bilinear method is wrong way to supervise subpixel because it is not the groundtruth.

It's not entirely strange. It can actually happen if the upsampling method is not good. And you can see if the renderings other than PSNR.

**Comment by qhdqhd** [comment]
> > 你做得好。顺便说一句，当渲染分辨率与输入分辨率相同时，你的方法能打败mipnerf吗？（抱歉我有点怀疑）因为我发现mipnerf也可以与supersample+NeRF进行比较。mipnerf 的行为几乎与 supersample 相同，但速度更快！而且supersample的方式貌似不一样，mipnerf只是在HR图上训练渲染，然后把HR下采样到LR，然后在LR图上评估PSNR，是不是太简单粗暴了？![@CXO$R(@8 @$R$4~$X4XY8](https://user-images.githubusercontent.com/42370719/224243525-60c3ffb2-30e3-4514-8a54-e96d454bd07d.png) ![RWAG)DO7A)T{8@G~B3J0F34](https://user-images.githubusercontent.com/42370719/224243688-ed5f8144-c9e0-4842-8a2b-d70dbde70354.png)
> 
> 我想在相同的输入分辨率下，我们的方法不能保证更好，但可能会达到类似的性能（虽然我也不确定）。mipnerf 中的超级采样与我们的略有不同，我们在 HR 图像上进行测试，但 mipnerf 的 ss 不会尝试推广到高于输入的分辨率。无论如何，超级采样可以合并到 mipnerf 甚至 instant-ngp 中。

Anyway, you did a nice work.
In my opinion, supersample is not elegant cause it cost more time. 
Mipnerf is truly elegant for me because my math is just so so.

**Comment by qhdqhd** [comment]
> > > > 我现在正在测试 nerfacto。我输入的视频是 750x750，我的 r
> > > 
> > > 
> > > 你在这个实验中使用了哪些数据集？也许你可以尝试一些排除双线性以外的其他上采方法。
> > 
> > 
> > 我自己的数据集。所以在你看来，这也奇怪吗？你之前尝试过这些实验吗？我可以推断的唯一原因是您在子像素上的监督方法是正确的方法。我的双线性方法是监督子像素的错误方法，因为它不是基本事实。
> 
> 这并不完全奇怪。如果上采样方法不好，它实际上可能会发生。并且你可以看到 PSNR 以外的效果图。

So did you experience the same thing? I am not sure if there is a better upsampling method than bilinear interpolation

**Comment by qhdqhd** [comment]
Can you reply me? I am working on my thesis now ... I need your help, thank you!

**Comment by cwchenwang** [comment]
> > > > > 我现在正在测试 nerfacto。我输入的视频是 750x750，我的 r
> > > > 
> > > > 
> > > > 你在这个实验中使用了哪些数据集？也许你可以尝试一些排除双线性以外的其他上采方法。
> > > 
> > > 
> > > 我自己的数据集。所以在你看来，这也奇怪吗？你之前尝试过这些实验吗？我可以推断的唯一原因是您在子像素上的监督方法是正确的方法。我的双线性方法是监督子像素的错误方法，因为它不是基本事实。
> > 
> > 
> > 这并不完全奇怪。如果上采样方法不好，它实际上可能会发生。并且你可以看到 PSNR 以外的效果图。
> 
> So did you experience the same thing? I am not sure if there is a better upsampling method than bilinear interpolation

You might try some deep learning upsampling methods.
