### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xqq21** [cwchenwang/NeRF-SR#9]
Thanks for your well-organized code. When I run wrap.py, an error is as follow::
  File "warp.py", line 189, in <module>
    ds = LLFFDataset(root_dir, result_dir, width, height)
  File "warp.py", line 31, in __init__
    self.read_meta()
  File "warp.py", line 112, in read_meta
    nerf_depth = np.load(os.path.join(self.result_dir, '{}-fine-depth-ori.npz'.format(i)))['arr_0']
  File "/home/xqq/anaconda3/envs/nerfsf/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/nerf-sr/llff-room-378x504-ni64-dp-ds2/30_val_vis/20-fine-depth-ori.npz'

![image](https://github.com/cwchenwang/NeRF-SR/assets/107976565/f2617e42-d387-4151-9e12-a5f2cc99e665)

l can't find the  file

**Comment by cwchenwang** [comment]
I guess your picture shows the `fine_depth_ori.npz` file for the fern scene? For other scenes, you can always run the first stage to obtain that file.

**Comment by xqq21** [comment]
Thank you! I hit one  error
